### ISSUE TITLE
Searchbar below FavoritesView

### ISSUE THREAD

**Issue by dl-alexandre** [dl-alexandre/SymbolGrid#2]
Search Button in ContextMenu must dismiss favorites view.

**Comment by kshitijhadke26** [comment]
Hi, could you please provide more details regarding the issue "Search Button in ContextMenu must dismiss favorites view"? Specifically, it would be helpful to understand:

What is the expected behavior when the search button is clicked?
How is the favorites view currently displayed, and what should happen to it when the search button is used?
Are there any specific use cases or steps to reproduce the issue?

Any additional information would be great to help me better address the issue. Thanks!

**Comment by dl-alexandre** [comment]
Hello, when an icon is selected then the symbol menu appears, either having a searchbar within that menu or placing a magnifying glass that opens the searchbar and dismisses the menu.

Hope that helps. Thanks

**Comment by dl-alexandre** [comment]
I have started Implementing search via the searchable modifier so this issue is no longer available.

**Comment by kshitijhadke26** [comment]
> I have started Implementing search via the searchable modifier so this issue is no longer available.

Okay.
